set(wxWidgets_LIB_DIR ${BUILD_ROOT}/stage/lib)
set(wxWidgets_ROOT_DIR ${BUILD_ROOT}/stage)
set(wxWidgets_USE_UNICODE ON)
set(wxWidgets_USE_UNIVERSAL OFF)
set(wxWidgets_USE_STATIC OFF)
set(wxWidgets_EXCLUDE_COMMON_LIBRARIES ON)

add_definitions("-DWXUSINGDLL")
if(WIN32)
    add_definitions("-D__WXMSW__")
elseif(__APPLE__)
    add_definitions("-D__")
else()
    add_definitions("-D__WXGTK__")
endif()

if(CMAKE_BUILD_TYPE MATCHES "Debug")
    set(wxWidgets_USE_DEBUG ON)
    add_definitions("-D__WXDEBUG__")
endif()
